encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("addentry", views.add_entry, name= "addentry"),
     path("randomentry", views.random_entry, name= "randomentry"),
    path("searchresult",views.search, name="searchresult"),
    path("edit",views.edit, name="edit"),
    path("editentry",views.edit_entry, name="editentry"),
    
]

encyclopedia/wiki/urls.py
from django.urls import path

from encyclopedia import views

urlpatterns = [
    
    path("<str:title>", views.entry, name ="entry")
  
 

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.wiki.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from cProfile import label
from email.policy import default
from hashlib import new
import attr
from django.urls import reverse
from django import forms
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, QueryDict


from random import randrange
from django.shortcuts import render

from . import util
from . import convert
import encyclopedia


class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label = "Title")
    MD_content =  forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":10}), label ="Markdown content")
  
   


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def add_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)    
        if form.is_valid():
            if form.cleaned_data["entry_title"] in util.list_entries():
                return render (request, "encyclopedia/error.html",{
                 "error_message":"Entry for " + form.cleaned_data["entry_title"] +" already exists!"})
            else:
                content = "# "+ form.cleaned_data["entry_title"] +"\n"+form.cleaned_data["MD_content"]
                util.save_entry(form.cleaned_data["entry_title"],content)
                return entry(request,form.cleaned_data["entry_title"])
    else:
        return render (request,"encyclopedia/addentry.html",{
        "form":NewEntryForm()})



def edit(request):
    qd =QueryDict()
    qd = request.GET
    form = NewEntryForm(initial={'entry_title' : qd["title"],
    'MD_content': util.get_entry(qd["title"])
    })
    return render (request, "encyclopedia/editentry.html",{
        "form": form})



def edit_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)    
        if form.is_valid():
                util.save_entry(form.cleaned_data["entry_title"], form.cleaned_data["MD_content"])
                return entry(request,form.cleaned_data["entry_title"])
    else:
        return render (request,"encyclopedia/addentry.html",{
        "form":NewEntryForm()})



def search(request):
    entries = util.list_entries()
    new_entries =[]
    qd =QueryDict()
    qd = request.GET
    search_query =""
    search_query = qd["q"]

    if search_query in entries:
         return entry(request, search_query)
    else:
        for e in entries:
            if search_query in e:
                new_entries.append(e)

    if len(new_entries)>0:
        return render(request, "encyclopedia/index.html", {
        "entries": new_entries
    })
    else:
        return render (request,"encyclopedia/error.html",{
        "error_message":"Entry for " + search_query +" does not exists!"})
    
    

def random_entry(request):
    entries = util.list_entries()
    i = randrange(0,len(entries)-1)
    return entry(request, entries[i])


def entry(request, title):
    entry_md =  util.get_entry(title)
    if entry_md is None:
        return render (request,"encyclopedia/error.html",{
            "error_message":"Entry does NOT exist!"})
    else:
        entry_html = convert.convertMDtoHTML(entry_md)
        return render (request,"encyclopedia/entry.html",{
            "entry_title":title, "entry_html":entry_html
        })

encyclopedia/templates/encyclopedia/addentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <form action="addentry" method="POST">
{{form}}

{% csrf_token%}
<input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/editentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{form.entry_title}}

{% endblock %}

{% block body %}
    <form action="editentry" method="POST">
{{form}}

{% csrf_token%}
<input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry_title}}
{% endblock %}

{% block body %}
{{ entry_html| safe }}
<br>
<br>

<a href="{% url 'encyclopedia:edit' %}?title={{entry_title}}"> Edit </a>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error!
{% endblock %}

{% block body %}
<h1> Error! </h1>
<h2>{{ error_message }}</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="searchresult" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:addentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomentry' %}">Random Page</a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>